author: 'Tom Meagher'
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'base'
description: "I’m Tom Meagher (MAH-hur): a programmer, blogger, and walk enthusiast living in NYC."
exclude:
  - '.gitignore'
  - 'CNAME'
  - 'LICENSE'
  - 'README.md'
  - 'sketch'
keywords: 'tom, tomfme, meagher, code, design, startups, technology, tech, design'
permalink: pretty
sass:
  style: compressed
  sass_dir: 'assets/styles'
timezone: America/New_York
title: Tom Meagher
url: "https://meagher.co"
